trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'react-app'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build React App'

- task: Docker@2
  inputs:
    containerRegistry: '<AzureContainerRegistryServiceConnection>'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '<Your Azure Subscription>'
    azureResourceGroup: '<Your Resource Group>'
    kubernetesCluster: '<Your AKS Cluster>'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'helm-chart/react-app'
    releaseName: 'react-app'
    valueFile: 'helm-chart/react-app/values.yaml'