trigger:
- main   # or your default branch like master

pool:
  name: college   # Same agent pool used in your classic pipeline

variables:
  imageName: 'portfolio1'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: 'sakshi-acr'       # ACR service connection name
    repository: '$(imageName)'            # Repo name in ACR
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'           # Adjust if Dockerfile is not in root
    tags: |
      $(Build.BuildId)
